### ISSUE TITLE
It (un)just doesn't work

### ISSUE THREAD

**Issue by OughtImpliesCan** [dtolstyi/node-chromium#16]
**`(node:3104) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/home/oughtimpliescan1/node_modules/selenium-webdriver/remote/index.js:251:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:3104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`**

So because I think it's bullshit to make people go through a million steps when it literally could be accomplished with a copy/paste of a single line into a command prompt, I've burned the calorie to make this as out of alignment (with the dominant coding culture that makes things unnecessarily difficult) as possible... My environment is a fresh Google Compute Engine f1-micro machine, debian...  Anybody know what to do?  I'm just trying the example WebDriver code on the main page and getting that error...

sudo wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1vFOz8NRHEpa1Qa4Cfi7hFW4GryrhBePB' -O chromiumInit;sudo chmod 755 chromiumInit;sudo ./chromiumInit;

**Comment by OughtImpliesCan** [comment]
**`Server terminated early with status 127
(node:3769) UnhandledPromiseRejectionWarning: TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at getRequestOptions (/home/oughtimpliescan1/node_modules/selenium-webdriver/http/index.js:50:21)
    at new HttpClient (/home/oughtimpliescan1/node_modules/selenium-webdriver/http/index.js:92:21)
    at url.then.url (/home/oughtimpliescan1/node_modules/selenium-webdriver/chrome.js:174:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:3769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`**

I actually modified the index.js file so that all of the new Promise( calls had a .then error handler... just to see what would happen, now I'm getting this error...

**Comment by dtolstyi** [comment]
Hi @OughtImpliesCan. Why did you decide to post your issue here?

**Comment by OughtImpliesCan** [comment]
If there's ever anybody in the future who comes looking for a way of "chromium node js" perhaps they will check the issues...  your thing doesn't work....  and I've described how everybody can use a very accessible environment (it's free on Google Cloud) to see exactly what happened...  lol, I posted it here because I really wanted this thing to work and it just didn't lol, spent like an hour total...  so frustrating... lol...  so much of software does that, oh just follow these steps and two hours later it turns out it just all falls apart at this step... and when it could all just be as simple as init this fresh environment and run this script and bam, everything is just there every single time...  how are we not at that paradigm yet?  that's a social thing...

**Comment by dtolstyi** [comment]
@OughtImpliesCan, I think you are mixing something. In all your logs I don't see any notice of `node-chromium` module but I see `selenium-webdriver` one. That's why I'm thinking that this is not a correct place for your issue.

**Comment by OughtImpliesCan** [comment]
this is the script that is downloaded in the one line copy paste
`sudo apt update;
                sudo apt-get update;
                sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -;
                sudo apt-get install -y nodejs;
                sudo npm install --save chromium chromedriver selenium-webdriver;
                sudo wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=12Lt31vER-mAs-3Xk-F9yZH_cTbbcnXco' -O chromiumTest.js;
                sudo chmod 755 chromiumTest.js;
                sudo node ./chromiumTest.js;`

**Comment by OughtImpliesCan** [comment]
![image](https://user-images.githubusercontent.com/22357393/59892151-d59c3700-938c-11e9-87bd-1c1b25dded19.png)

**Comment by OughtImpliesCan** [comment]
If you look at the file downloaded as chromiumTest.js you will see it is just the copy of the code you provided on the first page

**Comment by OughtImpliesCan** [comment]
This is the only place this issue should be shared as it's your thing that doesn't work

**Comment by dtolstyi** [comment]
I've just executed the same actions (except of removing multiple `sudo` and `chmod` which are not needed) and added latest `chromedriver` to the folder with the script and everything worked fine:
```
user@linux:/home/linux/node-chromium-test$ node chromiumTest.js
Hello Google!
Screenshot is saved
```

And here's the screenshot:
![google-start-page](https://user-images.githubusercontent.com/8183924/59905279-fd7bb100-9405-11e9-8f2c-2db397f139cf.png)

**Comment by dtolstyi** [comment]
Though, an error you mentioned: `Parameter "url" must be a string, not undefined at Url.parse` is very strange but you might be having an issue with `chromedriver` version so try downloading the latest one from here: http://chromedriver.chromium.org/downloads

**Comment by dtolstyi** [comment]
This library is used to get latest chromium binaries to your nodejs
project. Your issue seems to be connected to selenium-webdriver, so I still
think that this is not a correct place for this issue.

In plus, as mentioned in the previous message I did a test myself and
everything is fine.

**Comment by OughtImpliesCan** [comment]
> I've just executed the same actions (except of removing multiple `sudo` and `chmod` which are not needed) and added latest `chromedriver` to the folder with the script and everything worked fine:

So can you share the script for what you did exactly?  Right now we're sorta just taking your word for it and you can see what I did without just taking my word for it...

**Comment by dtolstyi** [comment]
@OughtImpliesCan I just used the same commands you provided earlier.

**Comment by OughtImpliesCan** [comment]
>  the same actions (except of removing multiple sudo and chmod which are not needed) and added latest chromedriver to the folder with the script

That's not the same thing I did... if you could figure out how to make this work for everybody in a freshly initialized standard development environment (debian cloud) instead of this nonsense of "oh I just did the same commands and it worked for me"... no, it needs to be from a fresh defacto public environment like Compute Engine, otherwise there's unnecessary ambiguity and it clearly isn't uniform behavior when it could be and as easy as copy paste one line into the shell... this is like blatant nonsense on an objective technical point... this coder culture of making things unnecessarily difficult when you literally could make it as simple as a single copy paste... culture is a cult... yuck!

**Comment by OughtImpliesCan** [comment]
> added latest `chromedriver` to the folder with the script

What does this mean?  Did you do it on the debian f1-micro?

**Comment by OughtImpliesCan** [comment]
If anybody comes along in the future, I never got this chromium node js package to work but I did find a way to use repl in the normal headless mode chrome ...

> Use the binary /opt/google/chrome/chrome directly not google-chrome which points to bash script /usr/bin/google-chrome.


https://stackoverflow.com/questions/45939872/headless-chrome-repl-not-working?rq=1

**Comment by dtolstyi** [comment]
> > added latest `chromedriver` to the folder with the script
> 
> What does this mean? Did you do it on the debian f1-micro?

I just downloaded the latest binary of chromedriver from official page.

> If anybody comes along in the future, I never got this chromium node js package to work but I did find a way to use repl in the normal headless mode chrome ...

Sorry, but I still don't understand what issues you got as far as there are hundreds of users who got no issues and I've recently tried it on a clean DigitalOcean Ubuntu server and everything worked fine.

In any case, I'm happy that you found a solution for yourself.

**Comment by OughtImpliesCan** [comment]
> > > added latest `chromedriver` to the folder with the script
> > 
> > 
> > What does this mean? Did you do it on the debian f1-micro?
> 
> I just downloaded the latest binary of chromedriver from official page.

Exactly... you're in a GUI personal environment with a bunch of other pre loaded stuff, you're not using a shell for everything, otherwise you would be giving CL instead of GUI browser instructions...  Again, this unnecessarily difficult thing...  This could be as simple as a single copy/paste in a shell prompt... it should be that, the fact that what is available on the internet isn't that means it's a shadow cartel thing... you cannot tell me it's an opinion that a single copy/paste into the same fresh (cloud facilitated) environment as the industry standard...

> 
> > If anybody comes along in the future, I never got this chromium node js package to work but I did find a way to use repl in the normal headless mode chrome ...
> 
> Sorry, but I still don't understand what issues you got as far as there are hundreds of users who got no issues 

Hundreds?  Just because someone doesn't comment doesn't mean they didn't have a problem...

> and I've recently tried it on a clean DigitalOcean Ubuntu server and everything worked fine.

https://console.cloud.google.com/compute
Start a fresh F1-micro machine and keep the Debian OS... it's very easy... if you run those commands we will be in the exact same environment without any assumed pre-configurations...  

> 
> In any case, I'm happy that you found a solution for yourself.

Actually the headless chrome package is having more issues as well...  Lol, for example, it doesn't just load the page like it would if you were in a browser (processing JS to complete the HTML) when you follow their instructions... like you could literally just use wget on the url and have the same... this is fucking bullshit... what could you possibly want with chrome on the server if it weren't to process the page as if it were an end user...

**Comment by dtolstyi** [comment]
@OughtImpliesCan Sorry but looks like you are just trolling now. You are writing absolutely unrelated and irrelevant comments. My server had no X installed at all so I don't know what kind of GUI you are talking about.
Headless Chrome does the thing it was created for perfectly (at least for me) so I don't know what you are talking about. It's working as a normal browser (except some features like extensions) so I don't see why would you say that it's same as wget.

This issues is closed now. If you want to talk you can contact me directly.
