### ISSUE TITLE
[feature suggestion] Ability to specify revision to download via environment variable

### ISSUE THREAD

**Issue by dhAlcojor** [dtolstyi/node-chromium#21]
It's problematic the way this project works currently, downloading always the latest version of Chromium available. In our case it is making out builds fail because the latest version of Chromium isn't compatible with the OS of our CI server.

My proposal is to allow to select a concrete revision to download in case something like this happens. I think it's really easy to implement and I have forked your repo and prepared some changes to use CHROMIUM_REVISION to select the revision to download.

Would you be open to study my PR?

**Comment by dtolstyi** [comment]
Thank you!
