### ISSUE TITLE
The `2.1.2` version is fails the audit

### ISSUE THREAD

**Issue by hadaabhi201** [dtolstyi/node-chromium#23]
**Repro Steps:**
Node version:`v12.12.0`

$ npm init -y

$ npm install --save chromium

> chromium@2.1.2 postinstall /Users/abhishekhada/Code/src/local/test-audit/node_modules/chromium
> node install.js

Step 1. Retrieving Chromium latest revision number
Step 2. Downloading Chromium (this might take a while). Revision number: 751348
Step 3. Setting up Chromium binaries
Process is successfully finished
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test-audit@1.0.0 No description
npm WARN test-audit@1.0.0 No repository field.

+ chromium@2.1.2
added 45 packages from 23 contributors and audited 48 packages in 12.252s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Expected:**

- install the chromium without any vulnerability issue.

**Actual**

- Audit failed.

**Comment by dtolstyi** [comment]
Hi @hadaabhi201,

I think these issues with `audit` has always been here as far as we haven't changed versions of packages for quite some time.
I'm trying to fix it but I'm having issues with latest version of `ava`. Somehow, it doesn't work fine for me.

If you are able to provide Pull Request with packages updates it would be great.

**Comment by hadaabhi201** [comment]
@dtolstyi ,

Same here, I am getting issue with `ava` too. The issue is with mkdrip. Once the issue is fixed on that package will update the package. There is already a MR for the issue:
https://github.com/maxogden/extract-zip/pull/85
Issue:

**Comment by dtolstyi** [comment]
Ha, so it's not my system. I'm having the same issue. Funny.
I've tried creating `.cache` folder manually but then it says: `Error: folder already exists`. Very frustrating))

OK, let's wait for the issue to be solved.

**Comment by dtolstyi** [comment]
All issues are fixed in version `2.2.0`.
