### ISSUE TITLE
caching the binary

### ISSUE THREAD

**Issue by ege24** [dtolstyi/node-chromium#24]
is there a way to cache the binary to shorten the time for npm ci? post build script always downloads a fresh copy, which I find unnecessary for an immutable binary blob.

**Comment by dtolstyi** [comment]
I'm not sure I fully understood. You normally download binaries only 1 time when you do `npm install`.

**Comment by ege24** [comment]
I was referring to npm ci. When you do a clean install, it deletes the node_modules and re-installs everything. However a binary dowload of chromium is immutable (AFAIK) so it shouldn't have to delete and re-download such a big file. It would make sense to cache it in a folder named %CHROMIUM_CACHE% or something, if it exists.

**Comment by dtolstyi** [comment]
I got your point @ege24. But for CI I thought it always starts from scratch, so it removes everything, creates fresh environment, gets latest code and performs build / deploy / testing, no?

**Comment by ege24** [comment]
in my case the VMs have access to a cache location, they also connect to a local, caching package server thanks to verdaccio. this step is the only one I can't seem to cache. not all builds servers have unlimited bandwidth, you know :)

**Comment by dtolstyi** [comment]
I see your point @ege24 . Unfortunately, I got no this feature in plans for the moment so if you could make a pull request with required changes I would be able to review and merge it.

**Comment by ege24** [comment]
sure I'll make a PR when I have time.

great to hear it'll be considered!

**Comment by dtolstyi** [comment]
Great! Thank you so much @ege24 ! 
Your help is very appreciated and for sure it won't be left without attention!

**Comment by dtolstyi** [comment]
This feature + optional download seems not very complicated but very interesting and might be useful. If someone is willing to implement it, it would be really great @ricksbrown @dhAlcojor @rcooney.

**Comment by ricksbrown** [comment]
@dtolstyi Yeah this could be useful for me, I took a look at it earlier, I might have a crack at it sometime.

**Comment by dtolstyi** [comment]
Thank you @ricksbrown !
P.S. New version is released. Feel free to update your dependencies.
