### ISSUE TITLE
Optional Download

### ISSUE THREAD

**Issue by honeo** [dtolstyi/node-chromium#25]
Apart from Postinstall, there is an API to optionally download chromium in It would be useful to have it.
It would be useful when using the same node_modules on different OSes

Currently, I use the following
```js
async function ensureChromium(){

	const NodeChromium = require('chromium');

	if( NodeChromium.path ){
		return NodeChromium.path;
	}else{
		await require('chromium/install.js');
		delete require.cache[require.resolve('chromium')];
		const _NodeChromium = require('chromium');
		return _NodeChromium.path;
	}

}
```

**Comment by dtolstyi** [comment]
Hi @honeo,
In PR #30 @ricksbrown has added possibility to access `install()` function of the module to facilitate what you are trying to achieve. You should be able to use it starting from the next version as soon as PR is merged.

**Comment by ricksbrown** [comment]
@honeo 

Further to what dtolstyi said above, if you still need it you should be able to do something like this:

```js
chromium.install().then(function() {
    // do stuff...
});
```

**Comment by honeo** [comment]
Thank you!
This is very useful for both CJS and ESM.

**Comment by ricksbrown** [comment]
@honeo We improved this some more in 3.0.1 - the `.path` property will now be reliably set after installation.
