### ISSUE TITLE
How to set CHROMIUM_REVISION

### ISSUE THREAD

**Issue by psociety** [dtolstyi/node-chromium#26]
I've tried to set it by using package.json:
```js
"scripts": {
    "preinstall": "export CHROMIUM_REVISION=729994",
}
```
```js
"scripts": {
    "preinstall": "CHROMIUM_REVISION=729994",
}
```
I've also tried setting `.npmrc`:
`CHROMIUM_REVISION=729994`

And during `npm i` it still gets ignored. They only way i found to make it work is by reinstalling it after install :S
```js
"scripts": {
    "setup": "export CHROMIUM_REVISION=729994 && npm install chromium"
  }
```

How can i set that ENV var so it's using during `npm i` ?

**Comment by dtolstyi** [comment]
From what I see, in the code it's used like this: 
```const chromiumRevision = process.env.CHROMIUM_REVISION;```
It means that it looks for an environment variable `CHROMIUM_REVISION`.
The reason why it's not defined for you should be in the way you are setting the variable. You need to be sure that this variable is available for your platform and the process of chromium installation.

You can play with `console.log(process.env);` to see which variables are actually set and how do they work.

P.S. I've never tried setting variables in `preinstall` so I can't tell you exactly which env is there and where do these variables go.

**Comment by dtolstyi** [comment]
One more way to set the variable is: `export CHROMIUM_REVISION=... && npm i`. The same as you do in your `setup` section of scripts but just by launching this in your app (instead of specifying inside script).
But, now, with your PR it should be easy to use `.npmrc`. Thank you.

**Comment by psociety** [comment]
@dtolstyi `export .. && npm` i was not an option because it means you must remember setting `export .. &&` everytime you don npm i :(

**Comment by dtolstyi** [comment]
Yes, you are absolutely right @psociety . Thank you for your PR!

**Comment by dtolstyi** [comment]
New version is released. Feel free to use `.npmrc` features now.
