### ISSUE TITLE
404 when downloading Windows snapshots

### ISSUE THREAD

**Issue by rcooney** [dtolstyi/node-chromium#5]
`npm install` fails on Windows because the file name of the snapshot zip changed from "chrome-win32.zip" to "chrome-win.zip" at revision 591479.

This is the URL that gets requested (and 404s) today https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F591828%2Fchrome-win32.zip?alt=media.

**Comment by dtolstyi** [comment]
Thank you! Could you make a pull request for this change, please?

**Comment by jmpresso** [comment]
@dtolstyi Would it be possible to merge that PR?

**Comment by dtolstyi** [comment]
Fixed by PR
